# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час розсилки')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='mailings', to='subscription.Subscriber')),
            ],
            options={
                'verbose_name': 'Розсилка',
                'verbose_name_plural': 'Розсилки',
            },
        ),
    ]
