# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 13:15
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('website', '0001_initial'), ('website', '0002_auto_20161116_2000'), ('website', '0003_auto_20161117_1215'), ('website', '0004_auto_20161118_1023'), ('website', '0005_project_content'), ('website', '0006_auto_20161118_1034'), ('website', '0007_event_content'), ('website', '0008_auto_20161118_1637'), ('website', '0009_auto_20161122_1511'), ('website', '0010_auto_20161122_1512')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '    Центри',
                'verbose_name': 'Центр',
                'db_table': 'website_centres',
            },
        ),
        migrations.CreateModel(
            name='CentreSubpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline_uk', models.CharField(max_length=100, verbose_name='Назва сторінки')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centres_subpages', to='website.Centre')),
            ],
            options={
                'verbose_name_plural': '   Підсторінки Центрів',
                'verbose_name': 'Підсторінка Центру',
                'db_table': 'website_centres_subpages',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('photo', models.ImageField(upload_to='cities/photos/', verbose_name='Фотографія')),
            ],
            options={
                'verbose_name_plural': '     Міста',
                'verbose_name': 'Місто',
                'db_table': 'website_cities',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=19, verbose_name='Телефон')),
                ('address_uk', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адреса')),
                ('centre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.Centre')),
            ],
            options={
                'verbose_name_plural': ' Контакти',
                'verbose_name': 'Контакт',
                'db_table': 'website_contacts',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=200, verbose_name='Назва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час події')),
                ('short_description_uk', models.CharField(max_length=500, verbose_name='Короткий опис')),
                ('slug', models.SlugField(editable=False)),
                ('image', models.ImageField(upload_to='events/images/', verbose_name='Головне зображення')),
            ],
            options={
                'verbose_name_plural': '     Події',
                'verbose_name': 'Подія',
                'db_table': 'website_events',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
            ],
            options={
                'verbose_name_plural': '      Категорії подій',
                'verbose_name': 'Категорія події',
                'db_table': 'website_events_categories',
            },
        ),
        migrations.CreateModel(
            name='IntroContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('headline_uk', models.CharField(max_length=50, verbose_name='Слоган')),
            ],
            options={
                'verbose_name_plural': '         Блок "Інтро"',
                'verbose_name': 'Блок "Інтро"',
                'db_table': 'website_content_intro',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_uk', models.CharField(max_length=100, verbose_name='Посада')),
                ('name_uk', models.CharField(max_length=200, verbose_name='Імʼя')),
                ('surname_uk', models.CharField(max_length=200, verbose_name='Прізвище')),
                ('photo', models.ImageField(upload_to='participants/photos/', verbose_name='Фотографія')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='website.Centre')),
            ],
            options={
                'verbose_name_plural': '  Співробітники',
                'verbose_name': 'Співробітник',
                'db_table': 'website_participants',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=200, verbose_name='Назва')),
                ('started_at', models.DateField(auto_now_add=True, verbose_name='Дата початку')),
                ('short_description_uk', models.CharField(max_length=500, verbose_name='Короткий опис')),
                ('slug', models.SlugField(editable=False)),
                ('image', models.ImageField(upload_to='projects/images/', verbose_name='Головне зображення')),
            ],
            options={
                'verbose_name_plural': '       Проекти',
                'verbose_name': 'Проект',
                'db_table': 'website_projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
            ],
            options={
                'verbose_name_plural': '        Напрямки проектів',
                'verbose_name': 'Напрямок проекту',
                'db_table': 'website_projects_areas',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.ProjectArea'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.EventCategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Project'),
        ),
        migrations.AddField(
            model_name='centre',
            name='events',
            field=models.ManyToManyField(blank=True, to='website.Event'),
        ),
        migrations.AddField(
            model_name='centre',
            name='projects',
            field=models.ManyToManyField(blank=True, to='website.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_uk',
            field=models.CharField(max_length=200, unique=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='centre',
            name='city',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.City'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_uk',
            field=ckeditor.fields.RichTextField(default='diy'),
        ),
        migrations.AddField(
            model_name='event',
            name='content_uk',
            field=ckeditor.fields.RichTextField(default='diy'),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=50, verbose_name='Назва мережі')),
                ('link', models.URLField(max_length=300, verbose_name='Посилання')),
                ('icon', models.CharField(max_length=20, verbose_name='Іконка')),
            ],
            options={
                'verbose_name_plural': '          Соціальні мережі',
                'verbose_name': 'Соціальна мережа',
                'db_table': 'website_socials',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=100, verbose_name='Назва організації')),
                ('link', models.URLField(max_length=300, verbose_name='Посилання')),
                ('logo', models.ImageField(upload_to='sponsors/logos/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name_plural': '           Донори',
                'verbose_name': 'Донор',
                'db_table': 'website_sponsors',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Подія', 'verbose_name_plural': '      Події'},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name': 'Категорія події', 'verbose_name_plural': '       Категорії подій'},
        ),
        migrations.AlterModelOptions(
            name='introcontent',
            options={'verbose_name': 'Інтро', 'verbose_name_plural': '            Інтро'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': '        Проекти'},
        ),
        migrations.AlterModelOptions(
            name='projectarea',
            options={'verbose_name': 'Напрямок проекту', 'verbose_name_plural': '         Напрямки проектів'},
        ),
        migrations.AlterField(
            model_name='event',
            name='content_uk',
            field=ckeditor.fields.RichTextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='website.EventCategory'),
        ),
        migrations.AlterField(
            model_name='event',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='website.Project'),
        ),
        migrations.AlterField(
            model_name='introcontent',
            name='headline_uk',
            field=models.CharField(max_length=200, verbose_name='Вступна фраза'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content_uk',
            field=ckeditor.fields.RichTextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='website.ProjectArea'),
        ),
        migrations.AlterModelTable(
            name='social',
            table='website_socials',
        ),
    ]
