# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_squashed_0010_auto_20161122_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='title_uk',
            new_name='title',
        ),
    ]
