# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '    Центри',
                'db_table': 'website_centres',
                'verbose_name': 'Центр',
            },
        ),
        migrations.CreateModel(
            name='CentreSubpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline_uk', models.CharField(max_length=100, verbose_name='Назва сторінки')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Centre')),
            ],
            options={
                'verbose_name_plural': '   Підсторінки Центрів',
                'db_table': 'website_centres_subpages',
                'verbose_name': 'Підсторінка Центру',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=100, verbose_name='Назва')),
                ('photo', models.ImageField(upload_to='cities/photos/', verbose_name='Фотографія')),
                ('centre', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Centre')),
            ],
            options={
                'verbose_name_plural': '     Міста',
                'db_table': 'website_cities',
                'verbose_name': 'Місто',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=19, verbose_name='Телефон')),
                ('address_uk', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адреса')),
                ('centre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.Centre')),
            ],
            options={
                'verbose_name_plural': ' Контакти',
                'db_table': 'website_contacts',
                'verbose_name': 'Контакт',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=200, verbose_name='Назва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час події')),
                ('short_description_uk', models.CharField(max_length=500, verbose_name='Короткий опис')),
                ('slug', models.SlugField(editable=False)),
                ('image', models.ImageField(upload_to='events/images/', verbose_name='Головне зображення')),
            ],
            options={
                'verbose_name_plural': '     Події',
                'db_table': 'website_events',
                'verbose_name': 'Подія',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name_plural': '      Категорії подій',
                'db_table': 'website_events_categories',
                'verbose_name': 'Категорія події',
            },
        ),
        migrations.CreateModel(
            name='IntroContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('headline_uk', models.CharField(max_length=50, verbose_name='Слоган')),
            ],
            options={
                'verbose_name_plural': '         Блок "Інтро"',
                'db_table': 'website_content_intro',
                'verbose_name': 'Блок "Інтро"',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_uk', models.CharField(max_length=100, verbose_name='Посада')),
                ('name_uk', models.CharField(max_length=200, verbose_name='Імʼя')),
                ('surname_uk', models.CharField(max_length=200, verbose_name='Прізвище')),
                ('photo', models.ImageField(upload_to='participants/photos/', verbose_name='Фотографія')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Centre')),
            ],
            options={
                'verbose_name_plural': '  Співробітники',
                'db_table': 'website_participants',
                'verbose_name': 'Співробітник',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=200, verbose_name='Назва')),
                ('started_at', models.DateField(auto_now_add=True, verbose_name='Дата початку')),
                ('short_description_uk', models.CharField(max_length=500, verbose_name='Короткий опис')),
                ('slug', models.SlugField(editable=False)),
                ('image', models.ImageField(upload_to='projects/images/', verbose_name='Головне зображення')),
            ],
            options={
                'verbose_name_plural': '       Проекти',
                'db_table': 'website_projects',
                'verbose_name': 'Проект',
            },
        ),
        migrations.CreateModel(
            name='ProjectArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name_plural': '        Напрямки проектів',
                'db_table': 'website_projects_areas',
                'verbose_name': 'Напрямок проекту',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.ProjectArea'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.EventCategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Project'),
        ),
        migrations.AddField(
            model_name='centre',
            name='events',
            field=models.ManyToManyField(to='website.Event'),
        ),
        migrations.AddField(
            model_name='centre',
            name='projects',
            field=models.ManyToManyField(to='website.Project'),
        ),
    ]
