# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20161116_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name_uk',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='title_uk',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_uk',
            field=models.CharField(max_length=200, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='projectarea',
            name='title_uk',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва'),
        ),
    ]
