# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20161117_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='centre',
        ),
        migrations.AddField(
            model_name='centre',
            name='city',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.City'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='events',
            field=models.ManyToManyField(blank=True, to='website.Event'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='projects',
            field=models.ManyToManyField(blank=True, to='website.Project'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.EventCategory'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.ProjectArea'),
        ),
    ]
