# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20161122_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centre',
            options={'verbose_name': 'Центр', 'verbose_name_plural': '        Центри'},
        ),
        migrations.AlterModelOptions(
            name='centresubpage',
            options={'verbose_name': 'Підсторінка Центру', 'verbose_name_plural': '       Підсторінки Центрів'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Місто', 'verbose_name_plural': '         Міста'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('created_at',), 'verbose_name': 'Подія', 'verbose_name_plural': '  Події'},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name': 'Категорія події', 'verbose_name_plural': '   Категорії подій'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Співробітник', 'verbose_name_plural': '      Співробітники'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('started_at',), 'verbose_name': 'Проект', 'verbose_name_plural': '    Проекти'},
        ),
        migrations.AlterModelOptions(
            name='projectarea',
            options={'verbose_name': 'Напрямок проекту', 'verbose_name_plural': '     Напрямки проектів'},
        ),
        migrations.AddField(
            model_name='city',
            name='photo_thumb',
            field=models.ImageField(null=True, upload_to='cities/photos/thumbs/', verbose_name='Фотографія'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Відображається'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Відображається'),
        ),
    ]
