# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20161128_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва діяльності')),
                ('icon', models.CharField(max_length=30, verbose_name='Іконка')),
            ],
            options={
                'verbose_name_plural': '          Види діяльності',
                'db_table': 'website_activities',
                'verbose_name': 'Вид діяльності',
            },
        ),
        migrations.AlterModelOptions(
            name='introcontent',
            options={'verbose_name': 'Інтро', 'verbose_name_plural': '             Інтро'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Соціальна мережа', 'verbose_name_plural': '           Соціальні мережі'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Донор', 'verbose_name_plural': '            Донори'},
        ),
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.CharField(max_length=30, verbose_name='Іконка'),
        ),
    ]
