# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 08:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20161118_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=ckeditor.fields.RichTextField(default='diy'),
            preserve_default=False,
        ),
    ]
