# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_project_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='content',
            new_name='content_uk',
        ),
    ]
