# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20161128_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='title',
            new_name='title_uk',
        ),
    ]
