# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 14:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20161118_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=ckeditor.fields.RichTextField(default='diy'),
            preserve_default=False,
        ),
    ]
