# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20161129_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='photo_thumb',
            field=models.ImageField(null=True, upload_to='participants/photos/thumbs/', verbose_name='Фотографія'),
        ),
    ]
