# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_event_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='content',
            new_name='content_uk',
        ),
    ]
