# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20161129_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': '      Контакти'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='centre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Centre'),
        ),
    ]
