# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20161129_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='short_description_uk',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description_uk',
        ),
        migrations.AddField(
            model_name='centre',
            name='short_description_uk',
            field=models.CharField(default='-', max_length=500, verbose_name='Короткий опис'),
            preserve_default=False,
        ),
    ]
