# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_worksheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='activity_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='У якій діяльності в рамках «ДІЙ!» ви би хотіли взяти участь?'),
        ),
    ]
