# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 21:54
from __future__ import unicode_literals

import act.services.file_name
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TwitterCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(upload_to=act.services.file_name.RandomFileName('metadata/images/'), verbose_name='Зображення')),
                ('url_name', models.CharField(max_length=100, verbose_name='Роутінг')),
                ('title_uk', models.CharField(max_length=100, verbose_name='Назва сторінки')),
                ('description_uk', models.CharField(max_length=250, verbose_name='Опис сторінки')),
                ('robots', models.CharField(max_length=100, verbose_name='Інформація для ботів')),
            ],
            options={
                'verbose_name_plural': 'Метадані',
                'verbose_name': 'Метадані',
            },
        ),
    ]
