# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 14:28
from __future__ import unicode_literals

import act.services.file_name
from django.db import migrations, models
import django.db.models.deletion
import metadata.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(metadata.models.MetadataAttributeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TwitterCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(metadata.models.MetadataAttributeMixin, models.Model),
        ),
        migrations.AddField(
            model_name='metadata',
            name='image',
            field=stdimage.models.StdImageField(default='-', upload_to=act.services.file_name.RandomFileName('metadata/images/'), verbose_name='Зображення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twittercard',
            name='metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metadata.Metadata'),
        ),
        migrations.AddField(
            model_name='opengraph',
            name='metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='open_graph', to='metadata.Metadata'),
        ),
    ]
