# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opengraph',
            options={'managed': False, 'verbose_name': 'OpenGraph', 'verbose_name_plural': 'OpenGraphs'},
        ),
        migrations.AlterModelOptions(
            name='twittercard',
            options={'managed': False, 'verbose_name': 'TwitterCard', 'verbose_name_plural': 'TwitterCards'},
        ),
    ]
