# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_opengraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opengraph',
            name='metadata',
        ),
    ]
