# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='checkout_hash_in',
            new_name='checkout_hash',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='checkout_hash_out',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='checkout_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата та час запиту'),
        ),
    ]
