# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-started_at', '-id'), 'verbose_name': 'Діяльність', 'verbose_name_plural': '    Діяльності'},
        ),
        migrations.AlterModelOptions(
            name='projectarea',
            options={'verbose_name': 'Напрямок діяльності', 'verbose_name_plural': '     Напрямки діяльностей'},
        ),
    ]
