# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title_uk', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text_uk', models.CharField(max_length=200, verbose_name='Текст')),
            ],
            options={
                'db_table': 'website_content_about',
                'verbose_name': 'Про нас',
                'verbose_name_plural': '              Про нас',
            },
        ),
        migrations.CreateModel(
            name='GoalContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title_uk', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text_uk', models.CharField(max_length=200, verbose_name='Текст')),
            ],
            options={
                'db_table': 'website_content_goal',
                'verbose_name': 'Мета',
                'verbose_name_plural': '             Мета',
            },
        ),
        migrations.AlterModelOptions(
            name='introcontent',
            options={'verbose_name': 'Інтро', 'verbose_name_plural': '               Інтро'},
        ),
        migrations.AlterModelOptions(
            name='worksheet',
            options={'verbose_name': 'Анкета', 'verbose_name_plural': ' Анкети'},
        ),
    ]
