# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 11:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centresubpage',
            name='content_uk',
            field=ckeditor.fields.RichTextField(default='-', verbose_name='Контент'),
            preserve_default=False,
        ),
    ]
