# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 14:17
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='photo',
            field=stdimage.models.StdImageField(upload_to='cities/photos/', verbose_name='Фотографія'),
        ),
    ]
