# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 09:59
from __future__ import unicode_literals

from django.db import migrations
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20161227_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='photo_thumb',
        ),
        migrations.AlterField(
            model_name='city',
            name='photo',
            field=website.models.FixedStdImageField(upload_to='cities/photos/', verbose_name='Фотографія'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=website.models.FixedStdImageField(upload_to='events/images/', verbose_name='Головне зображення'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=website.models.FixedStdImageField(upload_to='projects/images/', verbose_name='Головне зображення'),
        ),
    ]
