# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170205_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventattacheddocument',
            options={'verbose_name': 'Прикріплений документ', 'verbose_name_plural': 'Прикріплені документи'},
        ),
        migrations.AlterModelOptions(
            name='projectattacheddocument',
            options={'verbose_name': 'Прикріплений документ', 'verbose_name_plural': 'Прикріплені документи'},
        ),
    ]
