# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_centresubpage_content_uk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/', verbose_name='Документ')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='attached_documents',
            field=models.ManyToManyField(blank=True, related_name='projects', to='website.AttachedDocument'),
        ),
    ]
