# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170108_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcontent',
            options={'verbose_name': 'Контент - Про нас', 'verbose_name_plural': '              Контент - Про нас'},
        ),
        migrations.AlterModelOptions(
            name='goalcontent',
            options={'verbose_name': 'Контент - Мета', 'verbose_name_plural': '             Контент - Мета'},
        ),
        migrations.AlterModelOptions(
            name='introcontent',
            options={'verbose_name': 'Контент - Інтро', 'verbose_name_plural': '               Контент - Інтро'},
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='text_uk',
            field=models.TextField(max_length=2000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='goalcontent',
            name='text_uk',
            field=models.TextField(max_length=2000, verbose_name='Текст'),
        ),
    ]
