# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170108_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='activity',
            field=models.NullBooleanField(verbose_name='Чи бажаєте Ви долучитись до «ДІЙ!»?'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='problem',
            field=models.NullBooleanField(verbose_name='Бажаєте повідомити про проблему?'),
        ),
    ]
