# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170205_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-modified_at', '-id'), 'verbose_name': 'Діяльність', 'verbose_name_plural': '    Діяльності'},
        ),
        migrations.AddField(
            model_name='project',
            name='modified_at',
            field=models.DateField(auto_now=True, verbose_name='Дата оновлення'),
        ),
    ]
