# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 15:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170205_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='modified_at',
            field=models.DateField(default=datetime.datetime(2017, 2, 5, 17, 48, 34, 430738), verbose_name='Дата оновлення'),
        ),
    ]
