# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170114_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='social_link',
            field=models.URLField(blank=True, null=True, verbose_name='Соціальна мережа'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='link',
            field=models.URLField(verbose_name='Посилання'),
        ),
    ]
