# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170119_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='short_description_uk',
            field=models.CharField(max_length=1000, verbose_name='Короткий опис'),
        ),
    ]
