# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_scraping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraping',
            old_name='content',
            new_name='head',
        ),
        migrations.AlterField(
            model_name='scraping',
            name='path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterModelTable(
            name='scraping',
            table='website_scrapings',
        ),
    ]
