# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 08:52
from __future__ import unicode_literals

import act.services.file_name
from django.db import migrations
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20170207_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='photo',
        ),
        migrations.AddField(
            model_name='city',
            name='photo_fullscreen',
            field=website.models.FixedStdImageField(default='-', upload_to=act.services.file_name.RandomFileName('cities/photos/'), verbose_name='Фотографія (головна)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='photo_high',
            field=website.models.FixedStdImageField(default='-', upload_to=act.services.file_name.RandomFileName('cities/photos/'), verbose_name='Фотографія (висока)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='photo_square',
            field=website.models.FixedStdImageField(default='-', upload_to=act.services.file_name.RandomFileName('cities/photos/'), verbose_name='Фотографія (квадратна)'),
            preserve_default=False,
        ),
    ]
